### ISSUE TITLE
Sending flags for the second time shouldn't score

### ISSUE THREAD

**Issue by iqbalnur32** [Newman101/BeeCTF#36] opened 2020-06-13 11:00 UTC
Hallo sir minta maaf jika terganggu

When the User submits the flag and succeeds when he submits the same flag, for the second time the score should not increase but the alert flag is ready

ok thanks sir

**Comment by Newman101** [comment] 2020-06-13 13:10
Hi @iqbalnur32. Thanks for notifying me regarding this, your help is highly appreciated. I thought I had fixed this but apparently not. I'll have a look and fix.

**Comment by Newman101** [comment] 2020-06-13 14:08
Fixed couple of issues regarding this, needs further investigation.

**Comment by iqbalnur32** [comment] 2020-06-14 01:50
thank you for the response sir

**Comment by Newman101** [comment] 2020-06-14 12:26
Hi @iqbalnur32, that's now fixed. The issue was caused by wrong column being picked on the check against user's solved challenges.  I amended the column, so users are not able to submit the same flag twice any longer.

**Comment by iqbalnur32** [comment] 2020-06-14 22:46
Hi @iqbalnur32, that's now fixed. The issue was caused by wrong column being picked on the check against user's solved challenges. I amended the column, so users are not able to submit the same flag twice any longer.

thanks

**Comment by Newman101** [comment] 2020-06-15 09:04
Thanks for confirmation. Since this issue is confirmed to be resolved, I shall close it.

**Closed by Newman101** 2020-06-15 09:04 UTC
